### ISSUE TITLE
Error: Cannot find module 'colors'

### ISSUE THREAD

**Issue by jgallen23** [heapwolf/codesurgeon#6]
<pre>
[jga] ~/code/strf: npm install
codesurgeon@0.2.1 ./node_modules/codesurgeon
├── eyes@0.1.6
├── traverse@0.5.2
├── jslint-core@2011.01.09
├── uglify-js@1.0.7
└── jshint@0.5.3
[jga] ~/code/strf: node build.js

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'colors'
    at Function._resolveFilename (module.js:326:11)
    at Function._load (module.js:271:25)
    at require (module.js:355:19)
    at Object.<anonymous> (/home/jga/code/strf/node_modules/codesurgeon/lib/codesurgeon.js:3:14)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at require (module.js:355:19)
    at Object.<anonymous> (/home/jga/code/strf/build.js:2:19)
</pre>

**Comment by heapwolf** [comment]
thank you!! fixed in 8a2d9d40bd4dda208e7d78bda3a88f2f2425baa7
